default_url_options:
  host: 'vimemo.fly.dev'
  protocol: 'https'

smtp_settings:
  address: 'smtp.gmail.com'
  port: 587
  domain: 'gmail.com'
  user_name: <%= ENV['EMAIL_USER_NAME'] %>
  password: <%= ENV['EMAIL_PASSWORD'] %>
  authentication: 'plain'
  enable_starttls_auto: true

hosts:
  - 'vimemo.fly.dev'
  - 'vimemo.vercel.app'
  - 'vi-memo.com'

storage_service: 'amazon'
